# Ejercicio 1 - Tp2

Activar entorno virtual: source "nombre del ambiente"/bin/activate

Desactivar entorno virtual: deactivate

##### i) Descargar automáticamente ambos archivos.

Scatter-plot: cuanti-cuanti
Barras: cuanti-cuanti(representa frecuencias)
Box-plot: cuali-cuanti(representa cada cuanti, con una caja y sus errores/desvios)
Torta:Representa frecuencias entre cualquier par de variables.
Histograma: Barras individuales que tambien representan frecuencias.

In [20]:
from wget import download
from os import path

#Descargamos el archivo .txt de github en caso de que no exista en el directorio actual
if not path.exists("ObesityDataSet_raw_and_data_sinthetic.txt"):
    download("https://ignaciorlando.github.io/datasets/data-science/ObesityDataSet_raw_and_data_sinthetic.txt")
else:
    print("Ya existe el archivo.")

if not path.exists("ObesityDataSet_raw_and_data_sinthetic.csv"):
    download("https://ignaciorlando.github.io/datasets/data-science/ObesityDataSet_raw_and_data_sinthetic.csv")
else:
    print("Ya existe el archivo.")

Ya existe el archivo.
Ya existe el archivo.

ii) Leer el archivo de descripción y mostrar su contenido en pantalla.

In [35]:
with open("ObesityDataSet_raw_and_data_sinthetic.txt", "r", encoding="utf-8") as archivo:
    for linea in archivo:
        print(linea.rstrip())

Obesidad

La obesidad, que causa problemas físicos y mentales, es un problema de salud global con graves consecuencias. La prevalencia de la obesidad aumenta constantemente, por lo que se necesita nueva investigación que examine los factores que influyen en la obesidad y cómo predecir la aparición de la condición según estos factores.

Los datos fueron recolectados como parte de este trabajo científico: https://www.sciencedirect.com/science/article/pii/S2352340919306985#sec1

Información del Conjunto de Datos

Este conjunto de datos incluye información para la estimación de los niveles de obesidad en individuos de los países de México, Perú y Colombia, en función de sus hábitos alimenticios y condición física. Los datos contienen 17 atributos y 2111 registros, los registros están etiquetados con la variable de clase NObesidad (Nivel de Obesidad), que permite la clasificación de los datos utilizando los valores de Peso Insuficiente, Peso Normal, Sobrepeso Nivel I, Sobrepeso Nivel II, Obesidad Tipo I, Obesidad Tipo II y Obesidad Tipo III. El 77% de los datos se generó sintéticamente utilizando la herramienta Weka y el filtro SMOTE, el 23% de los datos se recolectaron directamente de los usuarios a través de una plataforma web.

Las columnas corresponden a:

Age: age

Height: height

Weight: weight

family_history_with_overweight: Has a family member suffered or suffers f from overweight? - yes or no

FAVC: Frequent consumption of high caloric food - yes or no

FCVC: Frequency of consumption of vegetables - Never, Sometimes, Always

NCP: Number of main meals - 1, 2, 3, 4

CAEC: Consumption of food between meals - No, Sometimes, Frequently, Always

SMOKE: Do you smoke - yes o no

CH2O: Consumption of water daily - Less than a litter, between 1 and 2 l, more than 2 l

SCC: Calories consumption monitoring - yes or no

FAF: Physical activity frequency - 0, 1 to 2, 2 to 4, 4 to 5

TUE: Time using technology devices - 0 to 2, 3 to 5, >5

CALC: Consumption of alcohol - no, sometimes, frequently, always

MTRANS: Transportation used - automobile, motorbike, bike, public_transportation, walking

NObeyesdad: Type of obesity - insufficient_weight, normal_weight, overweight-level_i, overweight-level_ii, obesity_type_i, obesity_type_ii, obesity_type_iii
BMI: Body mass index

In [27]:
import pandas as pd

# 1. Leer el archivo .txt
#El parámetro sep define la estructura: La función pd.read_csv() no juzga el archivo por su nombre, sino por cómo 
# están separados sus datos. Al usar sep="\t", le indicas que lea el texto dividiendo las columnas cada vez que 
# encuentre una tabulación.
df_txt = pd.read_csv("ObesityDataSet_raw_and_data_sinthetic.txt", sep="\t")

# 2. Exportarlo a un archivo .csv
df_txt.to_csv("ObesityDataSet.csv", index=False)

#Leemos el archivo .csv y lo convertimos a un DataFrame de pandas
df_csv = pd.read_csv("ObesityDataSet_raw_and_data_sinthetic.csv")

df_csv

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
0,21.000000,Female,1.620000,64.000000,no,no,2.0,3.0,no,no,2.000000,yes,0.000000,1.000000,Sometimes,Public_Transportation,Normal_Weight
1,21.000000,Female,1.520000,56.000000,Sometimes,no,3.0,3.0,yes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,23.000000,Male,1.800000,77.000000,Frequently,no,2.0,3.0,no,no,2.000000,yes,2.000000,1.000000,Sometimes,Public_Transportation,Normal_Weight
3,27.000000,Male,1.800000,87.000000,Frequently,no,3.0,3.0,no,no,2.000000,no,2.000000,0.000000,Sometimes,Walking,Overweight_Level_I
4,22.000000,Male,1.780000,89.800000,Sometimes,no,2.0,1.0,no,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,20.976842,Female,1.710730,131.408528,Sometimes,yes,3.0,3.0,no,no,1.728139,yes,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,21.982942,Female,1.748584,133.742943,Sometimes,yes,3.0,3.0,no,no,2.005130,yes,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,22.524036,Female,1.752206,133.689352,Sometimes,yes,3.0,3.0,no,no,2.054193,yes,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,24.361936,Female,1.739450,133.346641,Sometimes,yes,3.0,3.0,no,no,2.852339,yes,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,23.664709,Female,1.738836,133.472641,Sometimes,yes,3.0,3.0,no,no,2.863513,yes,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

### Analisis de las columnas del dataset:

Vemos que el dataset recopila datos de personas, mas particularmente está enfocado a la salud ya que mide variables que permiten analizar la misma. En la descripcion del dataset, podemos ver que está enfocado a medir la obesidad en mexico, peru y colombia.

AGE: Edad. Variable cuantitativa discreta.

Gender: Genero. Variable cualitativa nominal.

Height: Altura. Variable cuantitativa continua.

Weight: Peso. Variable cuantitativa nominal.

CALC: Consumision de alcohol. Variable cualitativa nominal.

FAVC: Frecuencia en consumir comida altamente calorica(si o no). Variable cualitativa dicotomica.

FCVC: Frecuencia en consumir vegetales(nunca, aveces, siempre). Variable cualitativa nominal.

NCP: Cantidad de comidas principales: Variable cuantitativa discreta.

SCC: Monitoreo del consumo de calorias(si o no). Variable cualitativa dicotomica.

SMOKE: Fuma(si o no). Variable cualitativa dicotomica.

CH20: Cantidad de agua bebida diaria. Variable cualitativa ordinal.

family_history_with_overweight(si o no): Variable cualitativa dicotomica.

FAF: Frecuencia de actividad fisica: Variable cualitativa ordinal.

TUE: Tiempo usando dispositivos tecnologicos: Variable cualitativa ordinal.

CAEC: Consumision entre comidas: Variable cualitativa ordinal.

MTRANS: Uso de transporte: Variable cualitativa nominal.

NObeysedad: Tipo de obesidad: Variable cualitativa ordinal.

iii) Leer el archivo de datos.

In [22]:
#Leemos el archivo csv y lo convertimos a un DataFrame de pandas
df_csv=pd.read_csv("ObesityDataSet_raw_and_data_sinthetic.csv")

#Imprimimos el DataFrame para ver su contenido
df_csv

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
0,21.000000,Female,1.620000,64.000000,no,no,2.0,3.0,no,no,2.000000,yes,0.000000,1.000000,Sometimes,Public_Transportation,Normal_Weight
1,21.000000,Female,1.520000,56.000000,Sometimes,no,3.0,3.0,yes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,23.000000,Male,1.800000,77.000000,Frequently,no,2.0,3.0,no,no,2.000000,yes,2.000000,1.000000,Sometimes,Public_Transportation,Normal_Weight
3,27.000000,Male,1.800000,87.000000,Frequently,no,3.0,3.0,no,no,2.000000,no,2.000000,0.000000,Sometimes,Walking,Overweight_Level_I
4,22.000000,Male,1.780000,89.800000,Sometimes,no,2.0,1.0,no,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,20.976842,Female,1.710730,131.408528,Sometimes,yes,3.0,3.0,no,no,1.728139,yes,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,21.982942,Female,1.748584,133.742943,Sometimes,yes,3.0,3.0,no,no,2.005130,yes,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,22.524036,Female,1.752206,133.689352,Sometimes,yes,3.0,3.0,no,no,2.054193,yes,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,24.361936,Female,1.739450,133.346641,Sometimes,yes,3.0,3.0,no,no,2.852339,yes,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,23.664709,Female,1.738836,133.472641,Sometimes,yes,3.0,3.0,no,no,2.863513,yes,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

iv) Imprimir la cabecera del archivo.

In [23]:
#Imprimimos la cabezera del archivo.
df_csv.head()

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
0,21.0,Female,1.62,64.0,no,no,2.0,3.0,no,no,2.0,yes,0.0,1.0,Sometimes,Public_Transportation,Normal_Weight
1,21.0,Female,1.52,56.0,Sometimes,no,3.0,3.0,yes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,23.0,Male,1.80,77.0,Frequently,no,2.0,3.0,no,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight
3,27.0,Male,1.80,87.0,Frequently,no,3.0,3.0,no,no,2.0,no,2.0,0.0,Sometimes,Walking,Overweight_Level_I
4,22.0,Male,1.78,89.8,Sometimes,no,2.0,1.0,no,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

v) Imprimir los primeros 5 registros del archivo.

In [24]:
#Leemos los primeros 5(aunque el head por defecto hace lo mismo, es decir, imprimir 5 registros)
df_csv.head(5)

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
0,21.0,Female,1.62,64.0,no,no,2.0,3.0,no,no,2.0,yes,0.0,1.0,Sometimes,Public_Transportation,Normal_Weight
1,21.0,Female,1.52,56.0,Sometimes,no,3.0,3.0,yes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,23.0,Male,1.80,77.0,Frequently,no,2.0,3.0,no,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight
3,27.0,Male,1.80,87.0,Frequently,no,3.0,3.0,no,no,2.0,no,2.0,0.0,Sometimes,Walking,Overweight_Level_I
4,22.0,Male,1.78,89.8,Sometimes,no,2.0,1.0,no,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

vi) Imprimir el resumen estadístico del mismo.

In [25]:
df_csv.describe()

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000
mean,24.312600,1.701677,86.586058,2.419043,2.685628,2.008011,1.010298,0.657866
std,6.345968,0.093305,26.191172,0.533927,0.778039,0.612953,0.850592,0.608927
min,14.000000,1.450000,39.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,19.947192,1.630000,65.473343,2.000000,2.658738,1.584812,0.124505,0.000000
50%,22.777890,1.700499,83.000000,2.385502,3.000000,2.000000,1.000000,0.625350
75%,26.000000,1.768464,107.430682,3.000000,3.000000,2.477420,1.666678,1.000000
max,61.000000,1.980000,173.000000,3.000000,4.000000,3.000000,3.000000,2.000000